In [144]:
import pandas as pd
import numpy as np

##Series


Series is a 1d array built on top of numpy

In [145]:
labels =  ['a', 'b', 'c']
list1 = [1, 2, 3]
arr = np.array([10, 20, 30])
d = {'a':1, 'b':2, 'c':3}

In [146]:
pd.Series(data= list1, index = labels)

a    1
b    2
c    3
dtype: int64

In [147]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [148]:
pd.Series(d)

a    1
b    2
c    3
dtype: int64

In [149]:
pd.Series(data = labels)

0    a
1    b
2    c
dtype: object

In [150]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [151]:
ser1 = pd.Series([1, 2, 3, 4], index = ['USA', 'UK', 'India', 'Australia'])

In [152]:
ser1

USA          1
UK           2
India        3
Australia    4
dtype: int64

In [153]:
ser2  = pd.Series([1, 2, 5, 6], ['USA', 'UK', 'India', 'Germany'])

In [154]:
ser2

USA        1
UK         2
India      5
Germany    6
dtype: int64

In [155]:
ser2['USA']

np.int64(1)

In [156]:
ser2['India']

np.int64(5)

In [157]:
ser1['USA']

np.int64(1)

In [158]:
ser1['India']

np.int64(3)

In [159]:
ser1 + ser2

Australia    NaN
Germany      NaN
India        8.0
UK           4.0
USA          2.0
dtype: float64

In [160]:
ser1 - ser2

Australia    NaN
Germany      NaN
India       -2.0
UK           0.0
USA          0.0
dtype: float64

In [161]:
ser1 * ser2

Australia     NaN
Germany       NaN
India        15.0
UK            4.0
USA           1.0
dtype: float64

In [162]:
ser1 / ser2

Australia    NaN
Germany      NaN
India        0.6
UK           1.0
USA          1.0
dtype: float64

##DataFrame

DataFrame is a 2d array with different data types, and DataFrame is more like a bunch of series put together.

In [163]:
from numpy.random import randn
np.random.seed(101)
df = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'Z Y X W'.split())
df


Z         Y         X         W
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [164]:
df['W']

A    0.503826
B    0.605965
C   -0.589001
D    0.955057
E    0.683509
Name: W, dtype: float64

In [165]:
df.W

A    0.503826
B    0.605965
C   -0.589001
D    0.955057
E    0.683509
Name: W, dtype: float64

In [166]:
df[['W', 'Z']]

W         Z
A  0.503826  2.706850
B  0.605965  0.651118
C -0.589001 -2.018168
D  0.955057  0.188695
E  0.683509  0.190794

In [167]:
type(df[['W', 'Z']])

pandas.core.frame.DataFrame

In [168]:
type(df['Y'])

pandas.core.series.Series

In [169]:
type(df)

pandas.core.frame.DataFrame

In [170]:
df['new'] = df['W'] + df.Y

In [171]:
df

Z         Y         X         W       new
A  2.706850  0.628133  0.907969  0.503826  1.131958
B  0.651118 -0.319318 -0.848077  0.605965  0.286647
C -2.018168  0.740122  0.528813 -0.589001  0.151122
D  0.188695 -0.758872 -0.933237  0.955057  0.196184
E  0.190794  1.978757  2.605967  0.683509  2.662266

In [172]:
# axis = 0 is for rows and axis = 1 for columns
df.drop('new', axis = 1)

Z         Y         X         W
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [173]:
df

Z         Y         X         W       new
A  2.706850  0.628133  0.907969  0.503826  1.131958
B  0.651118 -0.319318 -0.848077  0.605965  0.286647
C -2.018168  0.740122  0.528813 -0.589001  0.151122
D  0.188695 -0.758872 -0.933237  0.955057  0.196184
E  0.190794  1.978757  2.605967  0.683509  2.662266

In [174]:
df.drop('new', axis = 1, inplace = True)  # inplace = True means that the changes will be made in the original dataframe

In [175]:
df

Z         Y         X         W
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## iloc and loc

In [176]:
df.loc['A']          # loc is used to access the rows using labels

Z    2.706850
Y    0.628133
X    0.907969
W    0.503826
Name: A, dtype: float64

In [177]:
df.iloc[2]          # iloc is used to access the rows using index

Z   -2.018168
Y    0.740122
X    0.528813
W   -0.589001
Name: C, dtype: float64

In [178]:
df.loc['B', 'Y'] #rows, columns

np.float64(-0.31931804459303326)

In [179]:
df.loc[['A', 'B'], ['W', 'Y']]

W         Y
A  0.503826  0.628133
B  0.605965 -0.319318

In [180]:
df

Z         Y         X         W
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [181]:
df>0

Z      Y      X      W
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [182]:
df<0 # Boolean DataFrame

Z      Y      X      W
A  False  False  False  False
B  False   True   True  False
C   True  False  False   True
D  False   True   True  False
E  False  False  False  False

In [183]:
df[df>0]        # df>0 as a mask to filter out the values and True values are shown, and false values are replaced with NaN

Z         Y         X         W
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [184]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [185]:
df[df['W']>0]        #chain filtering

Z         Y         X         W
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [186]:
df[df['W']>0]
df[df['X']>0]

Z         Y         X         W
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509

In [187]:
df[df['W']>0]['Y'] #gets us the series Y for rows W>0

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: Y, dtype: float64

In [188]:
df[df['W']>0][['Z', 'Y']] #gets us the series Z, Y for rows W>0

Z         Y
A  2.706850  0.628133
B  0.651118 -0.319318
D  0.188695 -0.758872
E  0.190794  1.978757

In [189]:
df['Y']>1

A    False
B    False
C    False
D    False
E     True
Name: Y, dtype: bool

In [190]:
df[df['Y']>1]

Z         Y         X         W
E  0.190794  1.978757  2.605967  0.683509

In [191]:
df[(df['Y']>1) & (df['W']>0)]

Z         Y         X         W
E  0.190794  1.978757  2.605967  0.683509

In [192]:
df[(df['Y']>1) & (df['W'])>0][['X', 'Z']]

X         Z
E  2.605967  0.190794

In [193]:
import pandas as pd
import numpy as np

employee_data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Name': ['Alice Smith', 'Bob Johnson', 'Charlie Brown', 'Diana Prince', 'Eve Adams', 'Frank White', 'Grace Lee', 'Henry Clark'],
    'Department': ['HR', 'Engineering', 'Sales', 'Marketing', 'HR', 'Engineering', 'Sales', 'Marketing'],
    'Salary_USD': [65000, 95000, 70000, 72000, 68000, 98000, 75000, 73000],
    'Hire_Date': ['2022-01-15', '2021-03-01', '2023-06-20', '2022-11-10', '2023-02-28', '2021-09-01', '2022-04-10', '2023-01-05'],
    'Years_Experience': [3, 5, 2, 4, 3, 6, 4, 2]
}

df = pd.DataFrame(employee_data)

df.set_index('Employee_ID', inplace=True)

In [194]:
df

Name   Department  Salary_USD   Hire_Date  \
Employee_ID                                                       
101            Alice Smith           HR       65000  2022-01-15   
102            Bob Johnson  Engineering       95000  2021-03-01   
103          Charlie Brown        Sales       70000  2023-06-20   
104           Diana Prince    Marketing       72000  2022-11-10   
105              Eve Adams           HR       68000  2023-02-28   
106            Frank White  Engineering       98000  2021-09-01   
107              Grace Lee        Sales       75000  2022-04-10   
108            Henry Clark    Marketing       73000  2023-01-05   

             Years_Experience  
Employee_ID                    
101                         3  
102                         5  
103                         2  
104                         4  
105                         3  
106                         6  
107                         4  
108                         2

## **Questions**

1. Get the Hire_Date of Employee_ID 107 using loc.
2. Get the Years_Experience of the employee in the 2nd row (position 1) using iloc.
3. Get all columns for Employee_IDs 101, 103, and 106 using loc.
4. Get Name and Hire_Date for the last 4 employees using iloc.
5. Get Name and Years_Experience of employees with Salary_USD >= 95000 using loc.
6. Decrease Years_Experience by 1 for employees in 'HR'. Show their Name and updated Years_Experience using loc. (Use a copy!)
7. Get all rows, but only Department and Salary_USD columns using iloc.
8. Get Name and Hire_Date of employees with Years_Experience > 4 using loc.
9. Get all columns for the first and last employees (positions 0 and 7) using iloc.

In [195]:
# 1. Get the Hire_Date of Employee_ID 107 using loc.
df.loc[107, 'Hire_Date']

'2022-04-10'

In [196]:
# 2. Get the Years_Experience of the employee in the 2nd row (position 1) using iloc.
df.iloc[1]['Years_Experience']

np.int64(5)

In [197]:
# 3. Get all columns for Employee_IDs 101, 103, and 106 using loc.
df.loc[[101, 103, 106]]

Name   Department  Salary_USD   Hire_Date  \
Employee_ID                                                       
101            Alice Smith           HR       65000  2022-01-15   
103          Charlie Brown        Sales       70000  2023-06-20   
106            Frank White  Engineering       98000  2021-09-01   

             Years_Experience  
Employee_ID                    
101                         3  
103                         2  
106                         6

In [198]:
# 4. Get Name and Hire_Date for the last 4 employees using iloc.
df.iloc[-4:, [df.columns.get_loc('Name'), df.columns.get_loc('Hire_Date')]]

Name   Hire_Date
Employee_ID                         
105            Eve Adams  2023-02-28
106          Frank White  2021-09-01
107            Grace Lee  2022-04-10
108          Henry Clark  2023-01-05

In [199]:
# 5. Get Name and Years_Experience of employees with Salary_USD >= 95000 using loc.
df.loc[df['Salary_USD'] >= 95000, ['Name', 'Years_Experience']]

Name  Years_Experience
Employee_ID                               
102          Bob Johnson                 5
106          Frank White                 6

In [200]:
# 6. Decrease Years_Experience by 1 for employees in 'HR'. Show their Name and updated Years_Experience using loc. (Use a copy!)
hr_copy = df[df['Department'] == 'HR'].copy()
hr_copy

Name Department  Salary_USD   Hire_Date  Years_Experience
Employee_ID                                                                  
101          Alice Smith         HR       65000  2022-01-15                 3
105            Eve Adams         HR       68000  2023-02-28                 3

In [201]:
hr_copy['Years_Experience'] = hr_copy["Years_Experience"] - 1
hr_copy

Name Department  Salary_USD   Hire_Date  Years_Experience
Employee_ID                                                                  
101          Alice Smith         HR       65000  2022-01-15                 2
105            Eve Adams         HR       68000  2023-02-28                 2

In [202]:
# 7. Get all rows, but only Department and Salary_USD columns using iloc.
df.iloc[:, [1, 2]]

Department  Salary_USD
Employee_ID                         
101                   HR       65000
102          Engineering       95000
103                Sales       70000
104            Marketing       72000
105                   HR       68000
106          Engineering       98000
107                Sales       75000
108            Marketing       73000

In [203]:
# 8. Get Name and Hire_Date of employees with Years_Experience > 4 using loc.
df.loc[df['Years_Experience'] > 4 , ['Name', 'Hire_Date']]

Name   Hire_Date
Employee_ID                         
102          Bob Johnson  2021-03-01
106          Frank White  2021-09-01

In [204]:
# 9. Get all columns for the first and last employees (positions 0 and 7) using iloc.
df.iloc[[0, 7]]

Name Department  Salary_USD   Hire_Date  Years_Experience
Employee_ID                                                                  
101          Alice Smith         HR       65000  2022-01-15                 3
108          Henry Clark  Marketing       73000  2023-01-05                 2

In [205]:
from numpy.random import randn
np.random.seed(101)
df = pd.DataFrame(randn(5, 4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [206]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [207]:
newind = 'CA NY WY OR CO'.split()

In [208]:
df['States'] = newind

In [209]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [210]:
df.set_index('States', inplace = True)

In [211]:
df

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

## Multi Indexing

In [212]:
arrays = [
    ['North', 'North', 'South', 'South', 'East', 'East'],
    ['Widget', 'Gear', 'Widget', 'Gear', 'Widget', 'Gear']
]
index = pd.MultiIndex.from_arrays(arrays, names = ['Region', 'Product'])

In [213]:
data = {
    'Q1' : [150, 140, 130, 120, 123, 124],
    'Q2' : [132, 135, 136, 131, 127, 123]
}
df = pd.DataFrame(data, index = index)

In [214]:
df

Q1   Q2
Region Product          
North  Widget   150  132
       Gear     140  135
South  Widget   130  136
       Gear     120  131
East   Widget   123  127
       Gear     124  123

In [215]:
df.loc['North']

Q1   Q2
Product          
Widget   150  132
Gear     140  135

In [216]:
df.loc[('North', 'Widget')]

Q1    150
Q2    132
Name: (North, Widget), dtype: int64

In [217]:
df.xs('Widget', level = 'Product')

Q1   Q2
Region          
North   150  132
South   130  136
East    123  127

## Missing Data

In [218]:
df = pd.DataFrame({'A':[1, 2,np.nan],
                  'B':[5,np.nan,np.nan],
                   'C':[1,2,3]})

df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [219]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [220]:
df.dropna(thresh = 3)

A    B  C
0  1.0  5.0  1

In [221]:
df.dropna(thresh = 2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [222]:
df.dropna(thresh=2, axis=1)

A  C
0  1.0  1
1  2.0  2
2  NaN  3

In [223]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [224]:
df.fillna(value = df['A'].mean())

A    B  C
0  1.0  5.0  1
1  2.0  1.5  2
2  1.5  1.5  3

## Reading Data

In [225]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [226]:
df.head(1)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0

In [227]:
df2 = pd.read_html('https://www.fdic.gov/bank-failures/failed-bank-list')
df2[0]

Bank Name                City  \
0                        The Santa Anna National Bank          Santa Anna   
1                                Pulaski Savings Bank             Chicago   
2                  The First National Bank of Lindsay             Lindsay   
3               Republic First Bank dba Republic Bank        Philadelphia   
4                                       Citizens Bank            Sac City   
5                            Heartland Tri-State Bank             Elkhart   
6                                 First Republic Bank       San Francisco   
7                                      Signature Bank            New York   
8                                 Silicon Valley Bank         Santa Clara   
9                                   Almena State Bank              Almena   
10                         First City Bank of Florida   Fort Walton Beach   
11                               The First State Bank       Barboursville   
12                                 Ericson State Bank             Ericson   
13                   City National Bank of New Jersey              Newark   
14                                      Resolute Bank              Maumee   
15                              Louisa Community Bank              Louisa   
16                               The Enloe State Bank              Cooper   
17                Washington Federal Bank for Savings             Chicago   
18    The Farmers and Merchants State Bank of Argonia             Argonia   
19                                Fayette County Bank          Saint Elmo   
20  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
21                                     First NBC Bank         New Orleans   
22                                      Proficio Bank  Cottonwood Heights   
23                      Seaway Bank and Trust Company             Chicago   
24                             Harvest Community Bank          Pennsville   

            State   Cert                Acquiring Institution  \
0           Texas   5520            Coleman County State Bank   
1        Illinois  28611                      Millennium Bank   
2        Oklahoma   4134               First Bank & Trust Co.   
3    Pennsylvania  27332    Fulton Bank, National Association   
4            Iowa   8758            Iowa Trust & Savings Bank   
5          Kansas  25851               Dream First Bank, N.A.   
6      California  59017            JPMorgan Chase Bank, N.A.   
7        New York  57053                  Flagstar Bank, N.A.   
8      California  24735  First Citizens Bank & Trust Company   
9          Kansas  15426                          Equity Bank   
10        Florida  16748            United Fidelity Bank, fsb   
11  West Virginia  14361                       MVB Bank, Inc.   
12       Nebraska  18265           Farmers and Merchants Bank   
13     New Jersey  21111                      Industrial Bank   
14           Ohio  58317                   Buckeye State Bank   
15       Kentucky  58112    Kentucky Farmers Bank Corporation   
16          Texas  10716                   Legend Bank, N. A.   
17       Illinois  30570                   Royal Savings Bank   
18         Kansas  17719                          Conway Bank   
19       Illinois   1802            United Fidelity Bank, fsb   
20      Wisconsin  30003  First-Citizens Bank & Trust Company   
21      Louisiana  58302                         Whitney Bank   
22           Utah  35495                    Cache Valley Bank   
23       Illinois  19328                  State Bank of Texas   
24     New Jersey  34951  First-Citizens Bank & Trust Company   

         Closing Date  Fund  Sort ascending  
0       June 27, 2025                 10549  
1    January 17, 2025                 10548  
2    October 18, 2024                 10547  
3      April 26, 2024                 10546  
4    November 3, 2023                 10545  
5       July 28, 2023                 10544  
6         May 1, 2023       

In [228]:
df1 = df.copy()
df1

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [229]:
df.head()  #First 5 rows will display

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [230]:
df.tail()  #Last 5 rows will be displayed

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0

In [231]:
df['households'].unique()

array([ 606.,  277.,  495., ...,   92.,  607., 1036.])

**Sorting and Group by and Lexicographical order + Merge, Join + Concatenate**

## Concatenation

In [232]:
# String concatenation
FirstName = 'Pavan'
LastName = 'Velivela'
FullName = FirstName + ' ' + LastName
print(FullName)

Pavan Velivela


In [233]:
# List Concatenation
fruits = ['apple', 'mango', 'banana', 'strawberry']
vegetables = ['carrot', 'tomato', 'spinach']
food = fruits + vegetables
print(food)

['apple', 'mango', 'banana', 'strawberry', 'carrot', 'tomato', 'spinach']


In [234]:
address = ['123 Main Street', 'apt 101', 'New York', 'NY', '10001']
fulladdress = ', '.join(address)
print(fulladdress)

123 Main Street, apt 101, New York, NY, 10001


In [235]:
df1 = pd.DataFrame({
    'Name': ['Alice', 'Ray', 'Bob'],
    'Score': [99, 97, 95]
    })
df1

Name  Score
0  Alice     99
1    Ray     97
2    Bob     95

In [236]:
df2  = pd.DataFrame({
    'Name': ['Pavan', 'Raj', 'Ram'],
    'Score' : [96, 92, 91]
})
df2

Name  Score
0  Pavan     96
1    Raj     92
2    Ram     91

In [237]:
combined = pd.concat([df1, df2])
combined

Name  Score
0  Alice     99
1    Ray     97
2    Bob     95
0  Pavan     96
1    Raj     92
2    Ram     91

In [238]:
combined = pd.concat([df1, df2])
combined.loc[1]

Name  Score
1  Ray     97
1  Raj     92

In [239]:
combined = pd.concat([df1, df2], ignore_index = True )
combined

Name  Score
0  Alice     99
1    Ray     97
2    Bob     95
3  Pavan     96
4    Raj     92
5    Ram     91

In [240]:
combined.loc[1]

Name     Ray
Score     97
Name: 1, dtype: object

In [241]:
jan_data = pd.DataFrame({
    'Sales' : [1, 2, 3],
    'Expense' : [40, 50, 60]
    }, index = ['week1', 'week2', 'week3'])

feb_data = pd.DataFrame({
    'Sales' : [4, 5, 6],
    'Expense' : [23, 45, 56]
    }, index = ['week4', 'week5', 'week6'])

monthly_data = pd.concat([jan_data, feb_data], keys = [ 'Jan', 'Feb'])
monthly_data

Sales  Expense
Jan week1      1       40
    week2      2       50
    week3      3       60
Feb week4      4       23
    week5      5       45
    week6      6       56

 ## Sorting

In [242]:
import pandas as pd
import numpy as np

employee_data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Name': ['Alice Smith', 'Bob Johnson', 'Charlie Brown', 'Diana Prince', 'Eve Adams', 'Frank White', 'Grace Lee', 'Henry Clark'],
    'Department': ['HR', 'Engineering', 'Sales', 'Marketing', 'HR', 'Engineering', 'Sales', 'Marketing'],
    'Salary_USD': [65000, 95000, 70000, 72000, 68000, 98000, 75000, 73000],
    'Hire_Date': ['2022-01-15', '2021-03-01', '2023-06-20', '2022-11-10', '2023-02-28', '2021-09-01', '2022-04-10', '2023-01-05'],
    'Years_Experience': [3, 5, 2, 4, 3, 6, 4, 2]
}

df = pd.DataFrame(employee_data)

df.set_index('Employee_ID', inplace=True)
df

Name   Department  Salary_USD   Hire_Date  \
Employee_ID                                                       
101            Alice Smith           HR       65000  2022-01-15   
102            Bob Johnson  Engineering       95000  2021-03-01   
103          Charlie Brown        Sales       70000  2023-06-20   
104           Diana Prince    Marketing       72000  2022-11-10   
105              Eve Adams           HR       68000  2023-02-28   
106            Frank White  Engineering       98000  2021-09-01   
107              Grace Lee        Sales       75000  2022-04-10   
108            Henry Clark    Marketing       73000  2023-01-05   

             Years_Experience  
Employee_ID                    
101                         3  
102                         5  
103                         2  
104                         4  
105                         3  
106                         6  
107                         4  
108                         2

In [243]:
data = {
    'Class' : ['10', '9', '9', '8', '7', '9', '10', '12'],
    'Name' : ['Mahesh', 'Tarak', 'Bala', 'Prabhas', 'Charan', 'Arjun', 'Ram', 'Sudheer'],
    'Section': ['A', 'B', 'A', 'A', 'B', 'A', 'A', 'B'],
    'Score' : [91, 87, 98, 92, 85, 97, 94, 86]
    }

df = pd.DataFrame(data)
df

Class     Name Section  Score
0    10   Mahesh       A     91
1     9    Tarak       B     87
2     9     Bala       A     98
3     8  Prabhas       A     92
4     7   Charan       B     85
5     9    Arjun       A     97
6    10      Ram       A     94
7    12  Sudheer       B     86

In [244]:
df.sort_values(by= 'Class')

Class     Name Section  Score
0    10   Mahesh       A     91
6    10      Ram       A     94
7    12  Sudheer       B     86
4     7   Charan       B     85
3     8  Prabhas       A     92
1     9    Tarak       B     87
2     9     Bala       A     98
5     9    Arjun       A     97

In [245]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Class    8 non-null      object
 1   Name     8 non-null      object
 2   Section  8 non-null      object
 3   Score    8 non-null      int64 
dtypes: int64(1), object(3)
memory usage: 388.0+ bytes


In [246]:
df['Class'] = df['Class'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Class    8 non-null      int64 
 1   Name     8 non-null      object
 2   Section  8 non-null      object
 3   Score    8 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes


In [247]:
df.sort_values(by= 'Class')

Class     Name Section  Score
4      7   Charan       B     85
3      8  Prabhas       A     92
2      9     Bala       A     98
1      9    Tarak       B     87
5      9    Arjun       A     97
0     10   Mahesh       A     91
6     10      Ram       A     94
7     12  Sudheer       B     86

In [248]:
df.sort_values(by= 'Name')

Class     Name Section  Score
5      9    Arjun       A     97
2      9     Bala       A     98
4      7   Charan       B     85
0     10   Mahesh       A     91
3      8  Prabhas       A     92
6     10      Ram       A     94
7     12  Sudheer       B     86
1      9    Tarak       B     87

In [249]:
df.sort_values(by= 'Class', key = lambda x: x.astype(int))

Class     Name Section  Score
4      7   Charan       B     85
3      8  Prabhas       A     92
2      9     Bala       A     98
1      9    Tarak       B     87
5      9    Arjun       A     97
0     10   Mahesh       A     91
6     10      Ram       A     94
7     12  Sudheer       B     86

In [250]:
df.sort_values(by= 'Score', ascending = False)   # Default the score will be in ascending order

Class     Name Section  Score
2      9     Bala       A     98
5      9    Arjun       A     97
6     10      Ram       A     94
3      8  Prabhas       A     92
0     10   Mahesh       A     91
1      9    Tarak       B     87
7     12  Sudheer       B     86
4      7   Charan       B     85

In [251]:
df.sort_values(by= 'Section')

Class     Name Section  Score
0     10   Mahesh       A     91
2      9     Bala       A     98
3      8  Prabhas       A     92
5      9    Arjun       A     97
6     10      Ram       A     94
1      9    Tarak       B     87
4      7   Charan       B     85
7     12  Sudheer       B     86

In [252]:
df.sort_values(by= ['Section', 'Name'])

Class     Name Section  Score
5      9    Arjun       A     97
2      9     Bala       A     98
0     10   Mahesh       A     91
3      8  Prabhas       A     92
6     10      Ram       A     94
4      7   Charan       B     85
7     12  Sudheer       B     86
1      9    Tarak       B     87

In [253]:
df.sort_values(['Class', 'Section', 'Score'])

Class     Name Section  Score
4      7   Charan       B     85
3      8  Prabhas       A     92
5      9    Arjun       A     97
2      9     Bala       A     98
1      9    Tarak       B     87
0     10   Mahesh       A     91
6     10      Ram       A     94
7     12  Sudheer       B     86

In [254]:
df.sort_values(['Class', 'Section', 'Score'],
               key = lambda x: x.astype(int)
                if x.name == 'Class' else x,
               ascending = [True, True, False])

Class     Name Section  Score
4      7   Charan       B     85
3      8  Prabhas       A     92
2      9     Bala       A     98
5      9    Arjun       A     97
1      9    Tarak       B     87
6     10      Ram       A     94
0     10   Mahesh       A     91
7     12  Sudheer       B     86

In [255]:
df.sort_values(['Class', 'Section', 'Score'],
               key = lambda x: x.astype(int)
                if x.name == 'Class' else x,
               ascending = [True, True, True])

Class     Name Section  Score
4      7   Charan       B     85
3      8  Prabhas       A     92
5      9    Arjun       A     97
2      9     Bala       A     98
1      9    Tarak       B     87
0     10   Mahesh       A     91
6     10      Ram       A     94
7     12  Sudheer       B     86

In [256]:
df.sort_values(['Class', 'Score'],
               key = lambda x: x.astype(int)
                if x.name == 'Class' else x,
               ascending = [True, False])

Class     Name Section  Score
4      7   Charan       B     85
3      8  Prabhas       A     92
2      9     Bala       A     98
5      9    Arjun       A     97
1      9    Tarak       B     87
6     10      Ram       A     94
0     10   Mahesh       A     91
7     12  Sudheer       B     86

## Groupby

In [257]:
data = {
    'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
    'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
    'Sales': [200, 120, 340, 124, 243, 350]
}

df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [258]:
df.groupby('Company')['Sales'].agg(['sum', 'mean', 'count', 'min', 'max'])

sum   mean  count  min  max
Company                             
FB       593  296.5      2  243  350
GOOG     320  160.0      2  120  200
MSFT     464  232.0      2  124  340

In [259]:
df.groupby('Company')['Sales'].mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [260]:
def coeff_variation(x):
  return x.std()/x.mean() if x.mean() !=0 else 0

custom_agg = df.groupby('Company')['Sales'].agg(['sum', coeff_variation])
custom_agg



sum  coeff_variation
Company                      
FB       593         0.255179
GOOG     320         0.353553
MSFT     464         0.658341

In [261]:
df.groupby('Company')['Sales'].sum(numeric_only = True)

Company
FB      593
GOOG    320
MSFT    464
Name: Sales, dtype: int64

In [262]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [263]:
df.describe()

Sales
count    6.000000
mean   229.500000
std    100.899455
min    120.000000
25%    143.000000
50%    221.500000
75%    315.750000
max    350.000000

In [264]:
df.groupby('Company').describe().T    # T is transpose which changes rows to columns

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [265]:
df.groupby('Company').describe().T['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

In [266]:
df.groupby('Company')['Sales'].sum()

Company
FB      593
GOOG    320
MSFT    464
Name: Sales, dtype: int64

In [267]:
df.groupby('Company')['Sales'].transform('sum')   #transform function, takes the group statistics and gives a copy to each element in the group

0    320
1    320
2    464
3    464
4    593
5    593
Name: Sales, dtype: int64

In [268]:
company_avg_agg = df.groupby('Company')['Sales'].mean()
company_avg_agg

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [269]:
df['Company_Avg_Sales'] = df.groupby('Company')['Sales'].transform('mean')
df

Company   Person  Sales  Company_Avg_Sales
0    GOOG      Sam    200              160.0
1    GOOG  Charlie    120              160.0
2    MSFT      Amy    340              232.0
3    MSFT  Vanessa    124              232.0
4      FB     Carl    243              296.5
5      FB    Sarah    350              296.5

## Merge & Join

1. Merge combines data on columns *pd.merge*
2. Joincombined based on index *df.join*

In [270]:
employees = pd.DataFrame({
    'Employee_ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'DeptID': [1, 1, 2, 3]
})

departments = pd.DataFrame({
    'DeptID': [1, 2, 3],
    'DeptName': ['HR', 'IT', 'Finance']
})

salaries = pd.DataFrame({
    'Employee_ID': [101, 102, 104],
    'Salary': [70000, 80000, 75000]
})

In [271]:
employees

Employee_ID     Name  DeptID
0          101    Alice       1
1          102      Bob       1
2          103  Charlie       2
3          104    David       3

In [272]:
departments

DeptID DeptName
0       1       HR
1       2       IT
2       3  Finance

In [273]:
salaries

Employee_ID  Salary
0          101   70000
1          102   80000
2          104   75000

In [274]:
pd.merge(employees, departments, on ='DeptID')

Employee_ID     Name  DeptID DeptName
0          101    Alice       1       HR
1          102      Bob       1       HR
2          103  Charlie       2       IT
3          104    David       3  Finance

In [275]:
pd.merge(departments, employees, on ='DeptID')

DeptID DeptName  Employee_ID     Name
0       1       HR          101    Alice
1       1       HR          102      Bob
2       2       IT          103  Charlie
3       3  Finance          104    David

In [276]:
pd.merge(employees, salaries, on = 'Employee_ID')

Employee_ID   Name  DeptID  Salary
0          101  Alice       1   70000
1          102    Bob       1   80000
2          104  David       3   75000

In [277]:
pd.merge(salaries, employees, on = 'Employee_ID')

Employee_ID  Salary   Name  DeptID
0          101   70000  Alice       1
1          102   80000    Bob       1
2          104   75000  David       3

In [278]:
pd.merge(employees, salaries, on = 'Employee_ID', how ='right')

Employee_ID   Name  DeptID  Salary
0          101  Alice       1   70000
1          102    Bob       1   80000
2          104  David       3   75000

In [279]:
pd.merge(employees, salaries, on = 'Employee_ID', how ='left')

Employee_ID     Name  DeptID   Salary
0          101    Alice       1  70000.0
1          102      Bob       1  80000.0
2          103  Charlie       2      NaN
3          104    David       3  75000.0

In [280]:
pd.merge(employees, salaries, on = 'Employee_ID', how ='inner')

Employee_ID   Name  DeptID  Salary
0          101  Alice       1   70000
1          102    Bob       1   80000
2          104  David       3   75000

In [281]:
pd.merge(employees, salaries, on = 'Employee_ID', how ='outer')

Employee_ID     Name  DeptID   Salary
0          101    Alice       1  70000.0
1          102      Bob       1  80000.0
2          103  Charlie       2      NaN
3          104    David       3  75000.0

## Join

In [282]:
colors = pd.DataFrame({
    'color': ['red', 'green', 'blue'],
})

sizes = pd.DataFrame({
    'size': ['small', 'medium', 'large']
})

In [283]:
colors

color
0    red
1  green
2   blue